Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -10,37 +10,38 @@ jobs:
     runs-on: ubuntu-latest
     
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
-      
-    - name: Setup .NET
-      uses: actions/setup-dotnet@v2
-      with:
-        dotnet-version: '7.0.x'
-
-    - name: Restore dependencies
-      run: dotnet restore
-
-    - name: Build
-      run: dotnet build --configuration Release --no-restore
-
-    - name: Test
-      run: dotnet test --no-build --verbosity normal
-
-    - name: Build Docker image
-      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage:1 .
-
-    - name: Push Docker image
-      run: |
-        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
-        docker push ${{ secrets.DOCKER_USERNAME }}/myimage:1
+      - name: Checkout repository
+        uses: actions/checkout@v2
         
-    - name: Deploy to VPS using SSH keys
-      uses: appleboy/ssh-action@v0.1.2
-      with:
-        host: ${{ secrets.SSH_PRIVATE_IP }}
-        username: ${{ secrets.SSH_PRIVATE_NAME }}
-        key: ${{ secrets.SSH_PRIVATE_KEY }}
-        script: |
-          docker pull ${{ secrets.DOCKER_USERNAME }}/myimage:1
-          docker run -d --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/myimage:1
+      - name: Setup .NET
+        uses: actions/setup-dotnet@v2
+        with:
+          dotnet-version: '7.0.x'
+
+      - name: Restore dependencies
+        run: dotnet restore
+
+      - name: Build
+        run: dotnet build --configuration Release --no-restore
+
+      - name: Test
+        run: dotnet test --no-build --verbosity normal
+
+      - name: Build Docker image
+        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/myimage:1 .
+
+      - name: Push Docker image
+        run: |
+          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
+          docker push ${{ secrets.DOCKER_USERNAME }}/myimage:1
+          
+      - name: Deploy to VPS using SSH keys
+        uses: appleboy/ssh-action@v0.1.6 # Updated to the latest version
+        with:
+          host: ${{ secrets.SSH_PRIVATE_IP }}
+          username: ${{ secrets.SSH_PRIVATE_NAME }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: |
+            set -e  # Exit on error
+            docker pull ${{ secrets.DOCKER_USERNAME }}/myimage:1
+            docker run -d --restart unless-stopped ${{ secrets.DOCKER_USERNAME }}/myimage:1
